### ISSUE TITLE
Question: N + 1 Query issues

### ISSUE THREAD

**Issue by ALITHEALI** [AhmedElywa/prisma-tools#1]
Hello, 

This is a great package and thanks for creating this awesome package, now my question is that, does this package handle N + 1 Query issues?

Thanks a lot in advance.
Ali

**Comment by AhmedElywa** [comment]
The main thing we create this package is facing N + 1 query issue in my private project 
Idea here is convert `info: GraphQLResolveInfo` that has query fields come from frontend to be available prisma select object

Example query

```graphql
query {
  findOneUser(where: { id: 1 }) {
    id
    email
    name
    posts(
      where: { title: { contains: "a" } }
      orderBy: { createdAt: asc }
      first: 10
      skip: 5
    ) {
      id
      title
      comments(where: { contain: { contains: "a" } }) {
        id
        contain
      }
    }
  }
}
```
convert to
```json
{
  select: {
    id: true,
    email: true,
    name: true,
    posts: {
      select: {
        id: true,
        title: true,
        comments: {
          select: { id: true, contain: true },
          where: { contain: { contains: 'a' } }
        }
      },
      where: { title: { contains: 'a' } },
      orderBy: { createdAt: 'asc' },
      first: 10,
      skip: 5
    }
  }
```

with this way you just query what the frontend ask and save your performance 
and don't do a lot of `findOne`  for every relation result

**Comment by ALITHEALI** [comment]
Hello,

Very interesting! Thanks a lot for clearing that up. Is it possible to give an example for converting info to be available prisma select object (your suggested way)? 

Thanks a lot in advance!

**Comment by AhmedElywa** [comment]
It's already in my tools https://github.com/AhmedElywa/prisma-tools/tree/master/packages/select

**Comment by ALITHEALI** [comment]
This is great! Thanks a lot for all your amazing work!

**Comment by nghiepit** [comment]
I just wanted to say thank you for creating the `Prisma Select`!

**Comment by AhmedElywa** [comment]
@nghiepit Thank you for your positive feedback

**Comment by ielireb** [comment]
I have trouble with @@id. its giving me error.
