### ISSUE TITLE
Delete - Cannot read property 'find' of undefined.

### ISSUE THREAD

**Issue by danhollick** [AhmedElywa/prisma-tools#103]
When using the `Delete` package I get the following error.
`Cannot read property 'find' of undefined.`

My code looks like this:
```
    const prismaDelete = new PrismaDelete(
      context.prisma,
      path.join(process.cwd(), 'backend', 'prisma', 'schema.prisma')
    )
    await prismaDelete.onDelete({
      model: 'Invoice',
      where: { invoiceId: { in: id } },
    })
```

I think it' coming from [this line](https://github.com/AhmedElywa/prisma-tools/blob/7768df44341aa03170619eda4033d037e92ece2e/packages/delete/index.ts#L43):
```
    return this.schema.models.find((item) => item.name === modelName);
```
I think the problem is that `PrismaDelete` expects the schema to be of type `SchemaObject` from your `prisma-tools/select` package but I can't see anywhere that the schema is being parsed into that format? Am I missing something?

The docs also don't mention anything about needing to do that manually.

**Comment by AhmedElywa** [comment]
Sorry for this confusing I updated my tool to get schema as an object because converting .prisma file every request takes a long time and slow our server.
I just updated docs please take look here https://prisma-tools.ahmedelywa.com/delete/

**Comment by danhollick** [comment]
Okay cool. Might be nice for it fail with an error message in the future, especially because it depends on another package.
