### ISSUE TITLE
Contribution

### ISSUE THREAD

**Issue by wuichen** [AhmedElywa/prisma-tools#24]
Hi I would like to contribute to the project! This is awesome. I have written a small function called createfields that follows your other codes convention  to generate schema.json for admin based on prisma schema. Any guidelines of styles to send a pull request with new features?

**Comment by AhmedElywa** [comment]
You can send your pull request and add descriptions for your add i will see if it’s help or not then i will test it if everything is good will merge it 

Thanks for your work
